kind: pipeline
type: docker
name: default

steps:
- name: Docker build
  image: plugins/docker
  pull: never
  settings:
    repo: 0xb1b1/outlinegram
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
